const products = [
  {
    _id: '1',
    name: 'Skull Servant',
    image: '/images/Skull Servant.jpg',
    description:
      'A skeletal ghost that isn\'t strong but can mean trouble in large numbers.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 0.52,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Pot of Greed',
    image: '/images/Pot of Greed.jpg',
    description: 'Draw 2 cards.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 5.73,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Dark Magician',
    image: '/images/Dark Magician.jpg',
    description:
      'The ultimate wizard in terms of attack and defense.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 2.69,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Gaia the Fierce Knight',
    image: '/images/Gaia the Fierce Knight.jpg',
    description: 'A knight whose horse travels faster than the wind. His battle-charge is a force to be reckoned with.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 0.61,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Torrential Tribute',
    image: '/images/Torrential Tribute.jpg',
    description: 'When a monster(s) is Summoned: Destroy all monsters on the field.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 2.43,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Blue Eyes White Dragon',
    image: '/images/Blue Eyes White Dragon.jpg',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 53.66,
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Monster Reborn',
    image: '/images/Monster Reborn.jpg',
    description: 'Target 1 monster in either GY; Special Summon it.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 33.76,
    countInStock: 0,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '8',
    name: 'Mirror Force',
    image: '/images/Mirror Force.jpg',
    description: 'When an opponent\'s monster declares an attack: Destroy all your opponent\'s Attack Position monsters.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 2.75,
    countInStock: 4,
    rating: 4.5,
    numReviews: 8,
  },
  {
    _id: '9',
    name: 'King of the Skull Servants',
    image: '/images/Mirror Force.jpg',
    description: 'The original ATK of this card is the combined number of "King of the Skull Servants" and "Skull Servant" in your GY x 1000. When this card is destroyed by battle and sent to the GY: You can banish 1 other "King of the Skull Servants" or 1 "Skull Servant" from your GY; Special Summon this card.',
    brand: 'Yu-Gi-Oh',
    category: 'Card',
    price: 1.49,
    countInStock: 3,
    rating: 2.5,
    numReviews: 2,
  },
  {
    _id: '10',
    name: 'Iono\'s Voltorb',
    image: '/images/Mirror Force.jpg',
    description: 'Voltaic Chain 20+ This attack does 20 more damage for each [L] Energy attached to all of your Iono\'s Pokémon.',
    brand: 'Pokemon',
    category: 'Card',
    price: 0.23,
    countInStock: 1,
    rating: 1.5,
    numReviews: 1,
  },
  {
    _id: '11',
    name: 'Iono\'s Wattrel',
    image: '/images/Mirror Force.jpg',
    description: 'Quick Attack 10+ Flip a coin. If heads, this attack does 20 more damage.',
    brand: 'Pokemon',
    category: 'Card',
    price: 0.14,
    countInStock: 2,
    rating: 1,
    numReviews: 2,
  },
  {
    _id: '12',
    name: 'Pikachu ex',
    image: '/images/Mirror Force.jpg',
    description: 'C Tail Whap 30 LLC Thunder 220 This Pokémon also does 30 damage to itself.',
    brand: 'Pokemon',
    category: 'Card',
    price: 0.89,
    countInStock: 5,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '13',
    name: 'Charizard',
    image: '/images/Mirror Force.jpg',
    description: 'Ability: Energy Burn. As often as you like during your turn (before your attack), you may turn all [R] Energy attached to Charizard into [R] Energy for the rest of the turn. This power can\'t be used if Charizard is Asleep, Confused, or Paralyzed. RRRR Fire Spin 100. Discard 2 Energy cards attached to Charizard in order to use this attack.',
    brand: 'Pokemon',
    category: 'Card',
    price: 86.68,
    countInStock: 2,
    rating: 4.9,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Blastoise',
    image: '/images/Mirror Force.jpg',
    description: 'Ability: Vitality Spring. Once during your turn, you may search your deck for up to 6 Energy cards and attach them to your Pokémon in any way you like. Then, shuffle your deck. If you use this Ability, your turn ends.',
    brand: 'Pokemon',
    category: 'Card',
    price:0.64,
    countInStock: 12,
    rating: 4.1,
    numReviews: 25,
  },
  {
    _id: '15',
    name: 'Snubbull',
    image: '/images/Mirror Force.jpg',
    description: 'P Gnaw 10. PC Double-Edge 30 This Pokémon also does 10 damage to itself.',
    brand: 'Pokemon',
    category: 'Card',
    price: 0.04,
    countInStock: 23,
    rating: 1.1,
    numReviews: 2,
  },
  {
    _id: '16',
    name: 'Dragonite FB',
    image: '/images/Mirror Force.jpg',
    description: 'CCC Mach Blow 20 If the Defending Pokémon is a Pokémon SP, this attack\'s base damage is 80 instead of 20. CCCC Giant Tail 100. Flip a coin. If tails, this attack does nothing.',
    brand: 'Pokemon',
    category: 'Card',
    price: 3.98,
    countInStock: 3,
    rating: 3.9,
    numReviews: 8,
  },
  {
    _id: '17',
    name: 'Necropotence',
    image: '/images/Mirror Force.jpg',
    description: 'Skip your draw step. Whenever you discard a card, exile that card from your graveyard. Pay 1 life: Exile the top card of your library face down. Put that card into your hand at the beginning of your next end step.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 13.47,
    countInStock: 5,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '18',
    name: 'Rankle, Master of Pranks',
    image: '/images/Mirror Force.jpg',
    description: 'Flying, haste. Whenever Rankle deals combat damage to a player, choose any number — • Each player discards a card. • Each player loses 1 life and draws a card. • Each player sacrifices a creature of their choice.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 1.10,
    countInStock: 12,
    rating: 2.4,
    numReviews: 9,
  },
  {
    _id: '19',
    name: 'Forsworn Paladin',
    image: '/images/Mirror Force.jpg',
    description: 'Menace. Pay 1 life: Create a Treasure token. Target creature gets +2/+0 until end of turn. If mana from a Treasure was spent to activate this ability, that creature also gains deathtouch until end of turn.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 0.22,
    countInStock: 6,
    rating: 2.6,
    numReviews: 4,
  },
  {
    _id: '20',
    name: 'Thrun, the Last Troll',
    image: '/images/Mirror Force.jpg',
    description: 'This spell can\'t be countered. Hexproof (This creature can\'t be the target of spells or abilities your opponents control.)',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 1.54,
    countInStock: 2,
    rating: 3.2,
    numReviews: 1,
  },
  {
    _id: '21',
    name: 'Brainstorm',
    image: '/images/Mirror Force.jpg',
    description: 'Draw three cards, then put two cards from your hand on top of your library in any order.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 1.29,
    countInStock: 9,
    rating: 4.7,
    numReviews: 13,
  },
  {
    _id: '22',
    name: 'Time Warp',
    image: '/images/Mirror Force.jpg',
    description: 'プレイヤー１人を対象とする。そのプレイヤーは、このターンに続いて追加の１ターンを行う。',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 20.42,
    countInStock: 3,
    rating: 4.4,
    numReviews: 4,
  },
  {
    _id: '23',
    name: 'Liliana Vess',
    image: '/images/Mirror Force.jpg',
    description: '+1: Target player discards a card. −2: Search your library for a card, then shuffle and put that card on top. −8: Put all creature cards from all graveyards onto the battlefield under your control.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 15.25,
    countInStock: 2,
    rating: 4.2,
    numReviews: 7,
  },
  {
    _id: '24',
    name: 'Jace Beleren',
    image: '/images/Mirror Force.jpg',
    description: '+2: Each player draws a card. −1: Target player draws a card. −10: Target player mills twenty cards.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 1.50,
    countInStock: 4,
    rating: 3.1,
    numReviews: 14,
  },
  {
    _id: '25',
    name: 'Chandra Nalaar',
    image: '/images/Mirror Force.jpg',
    description: '+1: Chandra Nalaar deals 1 damage to target player or planeswalker. −X: Chandra Nalaar deals X damage to target creature. −8: Chandra Nalaar deals 10 damage to target player or planeswalker and each creature that player or that planeswalker’s controller controls.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 1.98,
    countInStock: 5,
    rating: 3.4,
    numReviews: 6,
  },
  {
    _id: '26',
    name: 'Doomsday (Amokhet Invocations)',
    image: '/images/Mirror Force.jpg',
    description: 'Search your library and graveyard for five cards and exile the rest. Put the chosen cards on top of your library in any order. You lose half your life, rounded up.',
    brand: 'Magic the Gathering',
    category: 'Card',
    price: 50.70,
    countInStock: 1,
    rating: 4.6,
    numReviews: 2,
  },
];

export default products;
