const products = [
    {
        _id: '1',
      name: 'Skull Servant',
      image: '/images/Skull Servant.jpg',
      description:
        'A skeletal ghost that isn\'t strong but can mean trouble in large numbers.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 0.52,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
        _id: '2',
      name: 'Pot of Greed',
      image: '/images/Pot of Greed.jpg',
      description: 'Draw 2 cards.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 5.73,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
    },
    {
        _id: '3',
      name: 'Dark Magician',
      image: '/images/Dark Magician.jpg',
      description:
        'The ultimate wizard in terms of attack and defense.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 2.69,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
        _id: '4',
      name: 'Gaia the Fierce Knight',
      image: '/images/Gaia the Fierce Knight.jpg',
      description: 'A knight whose horse travels faster than the wind. His battle-charge is a force to be reckoned with.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 0.61,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
        _id: '5',
      name: 'Torrential Tribute',
      image: '/images/Torrential Tribute.jpg',
      description: 'When a monster(s) is Summoned: Destroy all monsters on the field.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 2.43,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
        _id: '6',
      name: 'Blue Eyes White Dragon',
      image: '/images/Blue Eyes White Dragon.jpg',
      description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 53.66,
      countInStock: 5,
      rating: 4,
      numReviews: 12,
    },
    {
        _id: '7',
      name: 'Monster Reborn',
      image: '/images/Monster Reborn.jpg',
      description: 'Target 1 monster in either GY; Special Summon it.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 33.76,
      countInStock: 0,
      rating: 3.5,
      numReviews: 10,
    },
    {
        _id: '8',
      name: 'Mirror Force',
      image: '/images/Mirror Force.jpg',
      description: 'When an opponent\'s monster declares an attack: Destroy all your opponent\'s Attack Position monsters.',
      brand: 'Yu-Gi-Oh',
      category: 'Card',
      price: 2.75,
      countInStock: 4,
      rating: 4.5,
      numReviews: 8,
    },
  ];
  
  export default products;
  